services:
  ai-service:
    build: ./ai
    container_name: yolo-chef
    # ไม่เปิดพอร์ตออกข้างนอก ให้คุยผ่าน Network ภายในเท่านั้น

  web-gateway:
    image: nginx:alpine
    container_name: nginx-clerk
    ports:
      - "80:80"
    volumes:
      - ./web/index.html:/usr/share/nginx/html/index.html
      - ./web/nginx.conf:/etc/nginx/conf.d/default.conf
    depends_on:
      - ai-service